### ISSUE TITLE
Results missing

### ISSUE THREAD

**Issue by GitHubMLee** [riccardoklinger/Hqgis#76] opened 2023-10-12 01:10 UTC
Riccardo
Unfortunately this new version is not working properly. Pushing through a set of 43 points in a multiple address isochrone, the results vary but only return around 23 isochrones. However, on a machine that has an older version of the plugin, using the same settings, all 43 isochrones were returned.
Is this something you could look at?
Cheers
Matt

**Comment by riccardoklinger** [comment] 2023-10-16 14:27
can you provide a subset of two addresses (one working, one failing)?

**Comment by GitHubMLee** [comment] 2023-10-16 23:07
Riccardo

Attached is a gpkg file which has 43 point features.

Using your upgraded plugin, the file is selected in 'Isochrones - Multiple Addresses'. The chosen parameters are 'Destination', 'Time', '420 secs', 'Fast', 'Car' and with traffic 'Disabled'.

The results only capture isochrones for 23 of the points.

Using version 1.0.1, and with the same (or equivalent) parameters, all 43 results are returned.

Kind regards

Matt

**Comment by riccardoklinger** [comment] 2023-10-17 18:54
Sorry, please provide a link to your dataset. it was not uploaded to github.

**Comment by GitHubMLee** [comment] 2023-10-17 22:36
[NPBS for drivetimes.zip](https://github.com/riccardoklinger/Hqgis/files/12967968/NPBS.for.drivetimes.zip)

**Comment by riccardoklinger** [comment] 2023-10-18 04:56
Sorry @GitHubMLee , I cannot reconstruct your problem! 
<img width="1258" alt="grafik" src="https://github.com/riccardoklinger/Hqgis/assets/7377897/85436bad-45be-4d99-8b13-c0e266a03c82">
Here a geojson (change filetype on your drive) with the results:
[test-iso.json](https://github.com/riccardoklinger/Hqgis/files/12984704/test-iso.json)

**Comment by GitHubMLee** [comment] 2023-10-18 05:59
This is very frustrating. You can see in the image I have tested with various combinations of settings - traffic = enabled or disabled, type = fast or slow, origin/destination=start or destination. All of these combinations return different results, but when I use the old version of your plugin I get all 43 records!


<img width="1271" alt="HQGIS testing" src="https://github.com/riccardoklinger/Hqgis/assets/13372607/99682076-fcb4-48e9-b51b-2b1b1d34dd61">


The only other clue is this Python warning message:

<img width="674" alt="Python warning log" src="https://github.com/riccardoklinger/Hqgis/assets/13372607/e6435f74-3610-4125-9331-ca9859bb4202">

Does that help at all? Note that this issue occurs for all people in my organisation.

**Comment by riccardoklinger** [comment] 2023-10-24 19:45
in your "organization"? Are you using a freemium account? do you only use one key in your org? and: Which CRS are you using?  The message itself is jiust warning that the functionality is working but not covered anymore as it is deprecated.

**Comment by riccardoklinger** [comment] 2023-11-13 23:41
closing this issue as I was not able to reproduce the issue and no answer was given in 2 weeks

**Closed by riccardoklinger** 2023-11-13 23:41 UTC

**Comment by GitHubMLee** [comment] 2023-12-08 00:54
Sorry Riccardo, I know you have closed this because of my lack of response. The issue still occurs with us - intermittent issues with the new plugin sometimes not returning results. I have thought it may be an issue with our HERE migration but this seems okay as far as I can see. I've even created a new HERE project with a dedicated API key for isochrone, but the issue is still there. I may need to reach out to HERE on Slack. 
Yes, we have a pay as you go (the old 'Freemium' account at HERE).
So far we are using your older plugin, but I am aware that this is likely to be turned off at the HERE end as they force migration to the new v8 routing.
